# Usa la imagen oficial de Node.js como base para construir la aplicación
FROM node:18-alpine as build

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Pasar variables de entorno en build time
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

# Compila la aplicación de React
RUN npm run build

# Usa una imagen de Apache para servir la aplicación compilada
FROM httpd:latest

# Copia los archivos compilados de React al directorio de Apache
COPY --from=build /usr/src/app/build /usr/local/apache2/htdocs/

# Asegurarse que las llaves se copien al contenedor
COPY ./localhost.crt /usr/local/apache2/conf/
COPY ./localhost.key /usr/local/apache2/conf/

# Copia el archivo de configuración de SSL para Apache
COPY ./apache.conf /usr/local/apache2/conf/httpd.conf

# Exponer el puerto 443
EXPOSE 443

# Comando por defecto para ejecutar Apache en modo foreground
CMD ["httpd-foreground"]

