# Usa la imagen oficial de Node.js como base para construir la aplicación
FROM node:18-alpine as build

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json al contenedor
COPY package*.json ./

# Pasar variables de entorno en build time
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto del código fuente al contenedor
COPY . .

# Compila la aplicación de React
RUN npm run build

# Usa una imagen de Nginx para servir la aplicación compilada
FROM nginx:alpine

# Copia los archivos compilados de React desde la etapa de construcción al directorio de Nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Exponer el puerto que Nginx usará
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
